name: Android CI

on:
    push:
    pull_request:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
          - uses: actions/checkout@v3
          - uses: gradle/gradle-build-action@v3
          - name: Build and run unit tests with Gradle
            run: ./scripts/ci_unit.sh
